version: '3.1'

networks:
  local-network:
    driver: bridge

services:
  postgres:
    build: ./postgres
    container_name: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: s3cret
      POSTGRES_MULTIPLE_DATABASES: psqldb1,psqldb2
    networks:
      - local-network
  mysql:
    build: ./mysql
    container_name: "mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mysql
      MYSQL_PASSWORD: s3cret
      MYSQL_MULTIPLE_DATABASES: mysqldb1,mysqldb2
    networks:
      - local-network